openapi: 3.0.0
info:
  title: Protheus API
  version: '1.0'
  description: |-
    O conjunto de API's especialistas está hospedado no Talend ESB Runtime Container, instalado no SRV-INTEGRA.atech.local.
    Existem 3 ambientes.
  contact:
    name: Gustavo Regal
    email: gustavo@automatech.com.br
servers:
  - url: 'http://SRV-INTEGRA:8240.atech.local/services/Protheus/v1'
    description: DEV
  - url: 'http://SRV-INTEGRA:8140.atech.local/services/Protheus/v1'
    description: HML
  - url: 'http://SRV-INTEGRA:8040.atech.local/services/Protheus/v1'
    description: PROD
paths:
  /OrdemProducao/Criar:
    parameters: []
    post:
      summary: Criar ordem de produção
      operationId: post-OrdemProducao-Criar
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultId:
                    type: string
                    description: Número da OP gerada (C2_NUM)
                  resultCode:
                    type: string
                    description: 'Código de retorno devolvido pela API AtechExecAuto: em caso de sucesso = "000" (vide documentação).'
                  resultMessage:
                    type: string
                    description: Mensagem retornada pela API AtechExecAuto
                required:
                  - resultId
                  - resultCode
                  - resultMessage
              examples:
                Exemplo 1:
                  value:
                    resultId: '057344'
                    resultCode: '001'
                    resultMessage: Rotina automática executada com sucesso e com numeração automática gerada.
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      description: 'Cria uma ordem de produção (tabela SC2) no Protheus, através da API SyncMessage do AtechESB e da API AtechExecAuto no Protheus.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                empresa:
                  type: string
                  description: 'Formato "01"'
                filial:
                  type: string
                  description: 'Formato "01" (C2_FILIAL)'
                codigoProduto:
                  type: string
                  description: Código do produto no cadastro Protheus (C2_PRODUTO)
                quantidade:
                  type: number
                  description: Quantidade a ser produzida (C2_QUANT)
                previsaoInicio:
                  type: string
                  description: 'Data no formato dd/MM/aaaa. Se omitido, é utilizada a data atual do sistema (C2_DATPRI).'
                previsaoFim:
                  type: string
                  description: 'Data no formato dd/MM/aaaa. Se omitido, é utilizada a data atual do sistema (C2_DATPRF).'
                armazem:
                  type: string
                  description: 'Código do armazém no Protheus (campo C2_LOCAL). Se omitido, é usado "01".'
                prioridade:
                  type: string
                  description: 'Se omitido, é utilizado o padrão "500" (C2_PRIOR).'
                gerarEmpenhos:
                  type: boolean
                  description: 'Indica se o Protheus deve gerar automaticamente os empenhos para a OP, baseado no cadastro de estrutura de produtos (SG1). Se omitido, é considerado falso (parâmetro AUTEXPLODE).'
              required:
                - empresa
                - filial
                - codigoProduto
                - quantidade
            examples:
              Exemplo completo:
                value:
                  empresa: '01'
                  filial: '01'
                  codigoProduto: '02010432630102641'
                  previsaoInicio: 01/01/2020
                  previsaoFim: 31/12/2020
                  quantidade: 3.5
                  prioridade: '500'
                  armazem: '01'
                  gerarEmpenhos: false
              Exemplo essencial:
                value:
                  empresa: '01'
                  filial: '01'
                  codigoProduto: '02010432630102641'
                  quantidade: 3.5
        description: |-
          Corpo da requisição informando os dados da OP a ser criada.
          O método usa como data de emissão (C2_EMISSAO) a data atual do sistema conforme o servidor desta API.
      tags:
        - Ordens de produção
  /OrdemProducao/Excluir:
    parameters: []
    post:
      summary: Excluir ordem de produção
      operationId: post-OrdemProducao-Excluir
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultCode:
                    type: string
                    description: 'Código de retorno devolvido pela API AtechExecAuto: em caso de sucesso = "000" (vide documentação).'
                  resultMessage:
                    type: string
                    description: Mensagem retornada pela API AtechExecAuto
                required:
                  - resultCode
                  - resultMessage
              examples:
                Exemplo 1:
                  value:
                    resultCode: '000'
                    resultMessage: Rotina automática executada com sucesso.
        '201':
          description: ''
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      description: 'Exclui (exclusão lógica Protheus uma ordem de produção (tabela SC2) no Protheus, através da API SyncMessage do AtechESB e da API AtechExecAuto no Protheus.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                empresa:
                  type: string
                  description: 'Formato "01"'
                filial:
                  type: string
                  description: 'Formato "01" (C2_FILIAL)'
                numero:
                  type: string
                  description: Número da OP com 6 dígitos (C2_NUM)
                item:
                  type: string
                  description: 'Item da OP com 2 dígitos (C2_ITEM). Se omitido, é utilizado o padrão "01".'
                sequencia:
                  type: string
                  description: 'Sequência da OP com 3 dígitos (C2_SEQUEN). Se omitido, é utilizado o padrão "001".'
              required:
                - empresa
                - filial
                - numero
            examples:
              Exemplo completo:
                value:
                  empresa: '01'
                  filial: '01'
                  numero: '057318'
                  item: '01'
                  sequencia: '001'
              Exemplo essencial:
                value:
                  empresa: '01'
                  filial: '01'
                  numero: '057318'
        description: Corpo da requisição identificando a OP a ser excluída.
      tags:
        - Ordens de produção
components:
  schemas: {}
